Exercicio 3: back e front corrigidos
ThaispFelix/ExerciciosPHP pull request #16
Opened 2023-07-09 20:13 UTC by ThaispFelix

2023-07-13 12:09 UTC, edmargomes requested changes

2023-07-13 12:09 UTC, edmargomes commented on exercicio3-corrigido/index.php
> +   if (array_key_exists ('genero',$_POST) ){
esse if pode ser junto `array_key_exists ('idade',$_POST)  && array_key_exists ('genero',$_POST)`

2023-07-13 12:09 UTC, edmargomes commented on exercicio3-corrigido/index.php
> +        if ($idade) {
Nao tem a necessidade desse if pois vc ja fez o array_key_exists para a idade

2023-07-13 12:09 UTC, edmargomes commented on exercicio3-corrigido/index.php
> +        }
Pode remover

2023-07-18 16:15 UTC, ThaispFelix commented on exercicio3-corrigido/index.php
> +        if ($idade) {
Posso manter o if ($idade)? Sem ele quando se coloca o gênero feminino, sem a idade preenchida, acaba aceitando

2023-07-23 14:05 UTC, edmargomes approved these changes

2023-07-23 14:05 UTC, merged