Instalando codeception nas dependencias de desenvolvimento.
ThaispFelix/ExerciciosPHP pull request #25
Opened 2023-08-13 21:21 UTC by ThaispFelix

2023-08-17 21:11 UTC, revagomes commented on tests/Acceptance/Exercício6Cest.php
> +    public function ÍndiceExercicio6Test(AcceptanceTester $I)
Me parecer que  a letra I do início no nome do seu metodo está com acento agudo. 

Procure evitar letras com acentos em nomes de métodos, funções, variáveis.... pois isso pode causar erros na execução do código ou até mesmo erros de digitação.

Sugiro renomear este método de `ÍndiceExercicio6Test` para  `IndiceExercicio6Test`

2023-08-19 20:16 UTC, edmargomes requested changes
Seu teste esta otimo, somente faltou o teste se digitar um numero invalido e nao entendi pq esta comentado o $I->see

2023-08-19 20:16 UTC, edmargomes commented on tests/Acceptance/Exercício6Cest.php
> +    public function ÍndiceExercicio6Test(AcceptanceTester $I)
Remover esse arquivo Duplicado, tem um com Nome Exercício6Cest e outro sem acento, remover o com o acentuação

2023-08-20 18:49 UTC, edmargomes commented
Ja enviado no #26

2023-08-20 18:49 UTC, closed without merging