Nvt 409 exercicio2 frontend
ThaispFelix/ExerciciosPHP pull request #3
Opened 2023-04-17 02:05 UTC by ThaispFelix

2023-05-13 13:54 UTC, edmargomes requested changes

2023-05-13 13:54 UTC, edmargomes commented on exercicio2/style.CSS
> +    }
Ajustar identação

2023-05-13 13:54 UTC, edmargomes commented on exercicio2/index.php
> +<body>
Fechar o body e não abrir

2023-05-13 13:54 UTC, edmargomes commented on exercicio2/index.php
> +    <input type="submit" value="Enviar">
Ajustar identação

2023-05-17 03:17 UTC, ThaispFelix commented on exercicio2/index.php
> +<body>
Resolvido

2023-05-19 03:47 UTC, ThaispFelix commented on exercicio2/index.php
> +    <input type="submit" value="Enviar">
feito!

2023-05-19 03:47 UTC, ThaispFelix commented on exercicio2/style.CSS
> +    }
feito!

2023-05-22 02:45 UTC, edmargomes approved these changes

2023-05-22 02:45 UTC, merged