Nvt 410 exercicio2 backend
ThaispFelix/ExerciciosPHP pull request #4
Opened 2023-04-17 20:51 UTC by ThaispFelix

Depende da aprovação do NVT 409 exercicio2 frontend

2023-04-17 20:54 UTC, ThaispFelix commented
Depende da aprovação do NVT 409 exercicio 2 frontend

2023-05-13 17:32 UTC, edmargomes requested changes

2023-05-13 17:32 UTC, edmargomes commented on README.md
> +2. Rode o comando 'php -S localhost:8585'
Tem que rodar o docker certo? não o php -S

2023-05-13 17:32 UTC, edmargomes commented on exercicio2/index.php
> +
Retirar os espaços em branco

2023-05-13 17:32 UTC, edmargomes commented on exercicio2/index.php
> +           }
Ajustar a identação, algumas vezes tem espaço grande depois dentro do ifs menores o espaço é menor

2023-05-19 22:13 UTC, ThaispFelix commented on exercicio2/index.php
> +           }
Eu ajustei, mas não sei se realmente ficou do jeito que descreveu que deveria ficar. Pode olhar novamente, por favor?

2023-05-19 22:21 UTC, ThaispFelix commented on exercicio2/index.php
> +
feito!

2023-05-20 02:46 UTC, ThaispFelix commented on README.md
> +2. Rode o comando 'php -S localhost:8585'
Esse readme tá errado. O certo tá no exercício 3. Irei apagá-lo.

2023-05-29 00:33 UTC, edmargomes approved these changes

2023-05-29 00:33 UTC, merged